name: Build Arabic Letters Game APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test workflow
        run: echo "GitHub Actions is working"
